services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: dco-portal-mssql
    platform: linux/amd64 # force platform, so ARM machines to use emulation
    cap_add: ['SYS_PTRACE']
    user: root
    init: true
    environment:
      - 'ACCEPT_EULA=1'
      - 'MSSQL_SA_PASSWORD=DockerDatabaseP@22word!'
    ports:
      - 1433:1433
    hostname: mssql
    volumes:
      - ./packages/database/src/configuration/mssql.conf:/var/opt/mssql/mssql.conf
      - ./tmp/mssql-data:/var/opt/mssql/data
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: pins_azurite
    restart: always
    ports:
      - '10000:10000' # Blob
      - '10001:10001' # Queue
      - '10002:10002' # Table
    volumes:
      - ./data:/data
    command: >
      azurite
      --silent
      --location /data
      --blobHost 0.0.0.0
      --skipApiVersionCheck
