import { DOCUMENT_SUB_CATEGORY_ID } from '@pins/dco-portal-database/src/seed/data-static.ts';

export const OTHER_PLANS_DRAWINGS_SECTIONS_SUBCATEGORY_IDS = [
	DOCUMENT_SUB_CATEGORY_ID.SITE_LAYOUT_PLANS,
	DOCUMENT_SUB_CATEGORY_ID.ELEVATION_DRAWINGS,
	DOCUMENT_SUB_CATEGORY_ID.FLOOR_PLANS,
	DOCUMENT_SUB_CATEGORY_ID.CAR_PARKING_LANDSCAPING_ACCESS,
	DOCUMENT_SUB_CATEGORY_ID.DRAINAGE_AND_SURFACE_WATER_MANAGEMENT,
	DOCUMENT_SUB_CATEGORY_ID.OTHER_DETAILED_PLANS_AND_SECTIONS
];
