BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Case] ALTER COLUMN [projectConsentReason] NVARCHAR(2000) NULL;
ALTER TABLE [dbo].[Case] ALTER COLUMN [projectDescription] NVARCHAR(2000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
