import { DOCUMENT_SUB_CATEGORY_ID } from '@pins/dco-portal-database/src/seed/data-static.ts';

export const OTHER_ENVIRONMENTAL_DOCUMENTS_SUBCATEGORY_IDS = [
	DOCUMENT_SUB_CATEGORY_ID.INTRODUCTORY_CHAPTERS,
	DOCUMENT_SUB_CATEGORY_ID.ASPECT_CHAPTERS,
	DOCUMENT_SUB_CATEGORY_ID.ENVIRONMENTAL_STATEMENT_APPENDICES,
	DOCUMENT_SUB_CATEGORY_ID.ENVIRONMENTAL_STATEMENT_FIGURES,
	DOCUMENT_SUB_CATEGORY_ID.MODEL_INFORMATION,
	DOCUMENT_SUB_CATEGORY_ID.ANY_OTHER_MEDIA_INFORMATION,
	DOCUMENT_SUB_CATEGORY_ID.CONFIDENTIAL_DOCUMENTS,
	DOCUMENT_SUB_CATEGORY_ID.SENSITIVE_ENVIRONMENTAL_INFORMATION
];

export const OTHER_ENVIRONMENTAL_DOCUMENTS_SUBCATEGORY_ID_OPTIONS = [
	{ id: DOCUMENT_SUB_CATEGORY_ID.INTRODUCTORY_CHAPTERS, displayName: 'Introductory chapters' },
	{ id: DOCUMENT_SUB_CATEGORY_ID.ASPECT_CHAPTERS, displayName: 'Aspect chapters' },
	{
		id: DOCUMENT_SUB_CATEGORY_ID.ENVIRONMENTAL_STATEMENT_APPENDICES,
		displayName: 'Environmental statement appendices'
	},
	{ id: DOCUMENT_SUB_CATEGORY_ID.ENVIRONMENTAL_STATEMENT_FIGURES, displayName: 'Environmental statement figures' },
	{ id: DOCUMENT_SUB_CATEGORY_ID.MODEL_INFORMATION, displayName: 'Model information' },
	{ id: DOCUMENT_SUB_CATEGORY_ID.ANY_OTHER_MEDIA_INFORMATION, displayName: 'Any other media information' },
	{ id: DOCUMENT_SUB_CATEGORY_ID.CONFIDENTIAL_DOCUMENTS, displayName: 'Confidential documents' },
	{
		id: DOCUMENT_SUB_CATEGORY_ID.SENSITIVE_ENVIRONMENTAL_INFORMATION,
		displayName: 'Sensitive environmental information'
	}
];
